@clientId = 9a4e906f-7778-4c68-b86d-1c0f7f4370b8
POST {{host}}/client/{{clientId}}/connections
Authorization: Bearer {{adminToken}}
Content-Type: application/json

{
  "serverId": "00000000-0000-0000-0000-000000000000",
  "CountDays": 30
}