POST {{host}}/client/connections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJjZDY3ZWEwYy1jZjBmLTRlOGQtYmJhZS05YjkxMzhkYWNlMmQiLCJnaXZlbl9uYW1lIjoiRnJlYWsiLCJmYW1pbHlfbmFtZSI6IkZpc3RlciIsImp0aSI6ImQxMWIyYWMwLTMyOGUtNDJmOS05NWI5LTk2NWEyM2VkMzQ3YyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCIsImV4cCI6MTcwODAyOTQ3NywiaXNzIjoiRWFzeVZQTiIsImF1ZCI6IkVhc3lWUE4ifQ.UUBx3h3jPNU3CqFnpLIc6-B3Pl9N2GM4aD-H8uhJjms
//{{clientToken}}
Content-Type: application/json

{
    "serverId": "00000000-0000-0000-0000-000000000000",
    "CountDays": 30
}