POST {{host}}/my/connections/extend
Authorization: Bearer {{clientToken}}
Content-Type: application/json

{
    "connectionId": "00000001-0000-0000-0000-000000000000",
    "Days": 30,
    "Description": "I am payment this"
}