GET {{host}}/connections
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDAiLCJnaXZlbl9uYW1lIjoiRnJlYWsiLCJmYW1pbHlfbmFtZSI6IkZpc3RlciIsImp0aSI6ImUwM2ZjODc4LTZmMGQtNDBmYS04MmRkLThjYzUxMGRmMmY3YiIsImV4cCI6MTcwNzIzMzQ1OCwiaXNzIjoiRWFzeVZQTiIsImF1ZCI6IkVhc3lWUE4ifQ.UqzwYPBUzoik1qVEKLht-_93Uv2JnQaY_Hjgg-gkhPg