GET {{host}}/connections/7ba7083e-e0f6-413d-b65f-14084ceee13d/config
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhNDU1N2VkYy1hOTNjLTRiYzYtYjk3Ni03N2I0MjIxZWYwMzAiLCJnaXZlbl9uYW1lIjoiRnJlYWsiLCJmYW1pbHlfbmFtZSI6IkZpc3RlciIsImp0aSI6IjVlYmRjNDAwLWIzZTUtNDQ1Ni1hY2ZmLTllNjNjODU4MTczYyIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCIsImV4cCI6MTcwODAxODIzMiwiaXNzIjoiRWFzeVZQTiIsImF1ZCI6IkVhc3lWUE4ifQ.uGjoI3_HcHn5auCrtEAdAjJUFei1Y6ew31Zez-VZ-Yw
//{{superToken}}