version: '3.4'

networks:
  easy-vpn:
    driver: bridge

services:
  easy-vpn-database:
    image: postgres:16
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432"
    restart: always
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - easy-vpn

  easy-vpn-backend:
    image: easyvpn/backend:local
    depends_on:
      - easy-vpn-database
    container_name: backend
    ports:
      - "80"
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Postgres=User ID=postgres;Password=mysecretpassword;Host=database;Port=5432;
      - ASPNETCORE_URLS=http://+:80
    networks:
      - easy-vpn
    develop:
      watch:
        - action: rebuild
          path: backend/

  easy-vpn-frontend:
    image: easyvpn/frontend:local
    depends_on:
      - easy-vpn-backend
    container_name: frontend
    ports:
      - "3000"
    build:
      context: frontend/
      dockerfile: Dockerfile
    networks:
      - easy-vpn

  easy-vpn-proxy:
    image: nginx:mainline
    depends_on:
      - easy-vpn-backend
      - easy-vpn-frontend
    container_name: proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    networks:
      - easy-vpn

volumes:
  database_data:
