version: '3.4'

networks:
  easy-vpn:
    driver: bridge

services:

# ╔═══ REGION: Base infractructure services ═══╗
  easy-vpn-database:
    image: postgres:16
    container_name: database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mysecretpassword
    ports:
      - "5432"
    restart: unless-stopped
    volumes:
      - database_data:/var/lib/postgresql/data
    networks:
      - easy-vpn

  easy-vpn-backend:
    image: easyvpn/backend:latest
    depends_on:
      - easy-vpn-database
    container_name: backend
    ports:
      - "80"
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__Postgres=User ID=postgres;Password=mysecretpassword;Host=database;Port=5432;
      - ASPNETCORE_URLS=http://+:80
    restart: unless-stopped
    networks:
      - easy-vpn

  easy-vpn-frontend:
    image: easyvpn/frontend:latest
    depends_on:
      - easy-vpn-backend
    container_name: frontend
    ports:
      - "3000"
    build:
      context: frontend/
      dockerfile: Dockerfile
    restart: unless-stopped
    networks:
      - easy-vpn

  easy-vpn-proxy:
    image: nginx:mainline
    depends_on:
      - easy-vpn-backend
      - easy-vpn-frontend
    container_name: proxy
    ports:
      - "80:80"
    command: >
      /bin/sh -c "
        echo 'worker_processes 4;

        events {
            worker_connections 1024;
        }

        http {
            server {
                listen 80;

                location / {
                    proxy_pass http://frontend:3000;
                }

                location /api/ {
                    rewrite ^/api/(.*)$ /$1 break;
                    proxy_pass http://backend:80;
            }
            }
        }' > /etc/nginx/nginx.conf && nginx -g 'daemon off;'
      "
    restart: unless-stopped
    networks:
      - easy-vpn
# ╚═══ REGION: Base infractructure services ═══╝



# ╔═══ REGION: VPN services ═══╗
  wireguard-vpn-service:
    image: easyvpn/wireguard-vpn:latest
    container_name: wireguard-vpn-service
    environment:
      - SERVICE_HOST=89.191.226.158  # your host address
      - SERVICE_USER=user            # your user name for auth
      - SERVICE_PASSWORD=passwd      # your password for auth
    ports:
      - "51820:51820/udp"  # wireguard port
      - "8000:8000/tcp"    # http-api port
    volumes:
      - ~/.WireguardVpn:/etc/wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  amneziawg-vpn-service:
    image: easyvpn/amneziawg-vpn:latest
    container_name: amneziawg-vpn-service
    environment:
      - SERVICE_HOST=89.191.226.158  # your host address
      - SERVICE_USER=user            # your user name for auth
      - SERVICE_PASSWORD=passwd      # your password for auth
    ports:
      - "51840:51840/udp"  # amnezia wg port
      - "8010:8010/tcp"    # http-api port
    volumes:
      - ~/.AmneziaWgVpn:/etc/amnezia
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    devices:
      - "/dev/net/tun:/dev/net/tun"  # device mapping for TUN interface
    restart: unless-stopped
# ╚═══ REGION: VPN services ═══╝



# ╔═══ REGION: Other services ═══╗
  bot-service:
    image: easyvpn/bot:latest
    container_name: bot-service
    environment:
      - BOT_TOKEN=6618328943:AAEKMZYUJOliAEdBkibrhg8QMMy_xni-jEg
    restart: unless-stopped
# ╚═══ REGION: Other services ═══╝



volumes:
  database_data:
