@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMTI1ZjYzYS01OTE5LTRlOTEtYWI4MC02MjViNzVlZjc2YzgiLCJnaXZlbl9uYW1lIjoiRnJlYWsiLCJmYW1pbHlfbmFtZSI6IkZpc3RlciIsImp0aSI6ImM2NmE0ZWU2LTM5N2YtNGE0Yi04OTk2LTk2ZjA5MTQyMDBhNiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCIsImV4cCI6MTcxMjg3MDEwMSwiaXNzIjoiRWFzeVZQTiIsImF1ZCI6IkVhc3lWUE4ifQ.ZlacqxtNzYH7CZxRy-WfAk0PnkRi5CB9EWemPlFPQiY
GET {{host}}/auth/check
Authorization: Bearer {{token}}