@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMTI1ZjYzYS01OTE5LTRlOTEtYWI4MC02MjViNzVlZjc2YzgiLCJnaXZlbl9uYW1lIjoiRnJlYWsiLCJmYW1pbHlfbmFtZSI6IkZpc3RlciIsImp0aSI6IjgxYmVkNTJlLWUyYzEtNGUxZi1hNDcwLTc2ODU3YWYzMzMzNCIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkNsaWVudCIsImV4cCI6MTcxMjc1MTM4NCwiaXNzIjoiRWFzeVZQTiIsImF1ZCI6IkVhc3lWUE4ifQ.IQ5-DOW-OWNRXcgfhuUcVwDLgDQmg1iADnzD4pvOcVo

GET {{host}}/auth/check
Authorization: Bearer {{token}}