name: Dev deploy (self-hosted)
on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: [self-hosted, Linux, dev]
    steps:
    - name: Pull latest compose
      run: |
        cd /opt/EasyVPN.dev
        docker-compose --profile init pull
        
    - name: Restart Docker Compose
      run: |
        cd /opt/EasyVPN.dev 
        docker-compose --profile init up -d
