name: "Test single deploy"

on:
  pull_request:
    branches:
      - main 

jobs:
  build_compose:
    name: Build and Run 
    
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Replace service source
      run: |
          cp -r ./services/WireguardVpn /tmp/WireguardVpn 
          rm -rf .[^.]* ..?* *
          cp -r /tmp/WireguardVpn/* ./ 

    - name: Restore dependencies
      run: go mod download 

    - name: Build
      run: go build ./... 
      
    - name: Test
      run: go test ./...